// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: grpc/hospital.proto

package hospitalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gr
//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative grpc/*.proto
type DoctorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepartmentId int32 `protobuf:"varint,1,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	DiseaseId    int32 `protobuf:"varint,3,opt,name=diseaseId,proto3" json:"diseaseId,omitempty"`
	Status       bool  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DoctorsRequest) Reset() {
	*x = DoctorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_hospital_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorsRequest) ProtoMessage() {}

func (x *DoctorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_hospital_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorsRequest.ProtoReflect.Descriptor instead.
func (*DoctorsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_hospital_proto_rawDescGZIP(), []int{0}
}

func (x *DoctorsRequest) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DoctorsRequest) GetDiseaseId() int32 {
	if x != nil {
		return x.DiseaseId
	}
	return 0
}

func (x *DoctorsRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DepartmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiseaseId int32 `protobuf:"varint,1,opt,name=diseaseId,proto3" json:"diseaseId,omitempty"`
}

func (x *DepartmentRequest) Reset() {
	*x = DepartmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_hospital_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentRequest) ProtoMessage() {}

func (x *DepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_hospital_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentRequest.ProtoReflect.Descriptor instead.
func (*DepartmentRequest) Descriptor() ([]byte, []int) {
	return file_grpc_hospital_proto_rawDescGZIP(), []int{1}
}

func (x *DepartmentRequest) GetDiseaseId() int32 {
	if x != nil {
		return x.DiseaseId
	}
	return 0
}

type DepartmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	DiseaseId   int32  `protobuf:"varint,4,opt,name=DiseaseId,proto3" json:"DiseaseId,omitempty"`
}

func (x *DepartmentResponse) Reset() {
	*x = DepartmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_hospital_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentResponse) ProtoMessage() {}

func (x *DepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_hospital_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentResponse.ProtoReflect.Descriptor instead.
func (*DepartmentResponse) Descriptor() ([]byte, []int) {
	return file_grpc_hospital_proto_rawDescGZIP(), []int{2}
}

func (x *DepartmentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DepartmentResponse) GetDiseaseId() int32 {
	if x != nil {
		return x.DiseaseId
	}
	return 0
}

type DoctorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId     int32   `protobuf:"varint,1,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	FirstName    string  `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName     string  `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Patronymic   string  `protobuf:"bytes,4,opt,name=patronymic,proto3" json:"patronymic,omitempty"`
	DepartmentId int32   `protobuf:"varint,5,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	Price        float64 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *DoctorsResponse) Reset() {
	*x = DoctorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_hospital_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorsResponse) ProtoMessage() {}

func (x *DoctorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_hospital_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorsResponse.ProtoReflect.Descriptor instead.
func (*DoctorsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_hospital_proto_rawDescGZIP(), []int{3}
}

func (x *DoctorsResponse) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *DoctorsResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *DoctorsResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *DoctorsResponse) GetPatronymic() string {
	if x != nil {
		return x.Patronymic
	}
	return ""
}

func (x *DoctorsResponse) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DoctorsResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_grpc_hospital_proto protoreflect.FileDescriptor

var file_grpc_hospital_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x6a, 0x0a, 0x0e, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x31, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x12, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x44, 0x69, 0x73, 0x65, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x22, 0xc1, 0x01, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x61, 0x74, 0x72, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x74, 0x72, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63, 0x12, 0x22,
	0x0a, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x9f, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4d, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x44, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x5c, 0x46, 0x72, 0x69, 0x6e, 0x67, 0x30, 0x32,
	0x5c, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5c, 0x67, 0x72, 0x70, 0x63, 0x5c, 0x68, 0x6f, 0x73, 0x70,
	0x69, 0x74, 0x61, 0x6c, 0x70, 0x62, 0x3b, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_hospital_proto_rawDescOnce sync.Once
	file_grpc_hospital_proto_rawDescData = file_grpc_hospital_proto_rawDesc
)

func file_grpc_hospital_proto_rawDescGZIP() []byte {
	file_grpc_hospital_proto_rawDescOnce.Do(func() {
		file_grpc_hospital_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_hospital_proto_rawDescData)
	})
	return file_grpc_hospital_proto_rawDescData
}

var file_grpc_hospital_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_hospital_proto_goTypes = []interface{}{
	(*DoctorsRequest)(nil),     // 0: grpc.DoctorsRequest
	(*DepartmentRequest)(nil),  // 1: grpc.DepartmentRequest
	(*DepartmentResponse)(nil), // 2: grpc.DepartmentResponse
	(*DoctorsResponse)(nil),    // 3: grpc.DoctorsResponse
}
var file_grpc_hospital_proto_depIdxs = []int32{
	0, // 0: grpc.DepartmentService.GetDoctors:input_type -> grpc.DoctorsRequest
	1, // 1: grpc.DepartmentService.GetDepartmentByDiseaseId:input_type -> grpc.DepartmentRequest
	3, // 2: grpc.DepartmentService.GetDoctors:output_type -> grpc.DoctorsResponse
	2, // 3: grpc.DepartmentService.GetDepartmentByDiseaseId:output_type -> grpc.DepartmentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_hospital_proto_init() }
func file_grpc_hospital_proto_init() {
	if File_grpc_hospital_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_hospital_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_hospital_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_hospital_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_hospital_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_hospital_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_hospital_proto_goTypes,
		DependencyIndexes: file_grpc_hospital_proto_depIdxs,
		MessageInfos:      file_grpc_hospital_proto_msgTypes,
	}.Build()
	File_grpc_hospital_proto = out.File
	file_grpc_hospital_proto_rawDesc = nil
	file_grpc_hospital_proto_goTypes = nil
	file_grpc_hospital_proto_depIdxs = nil
}
